tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key

  options:
    default:
      minVersion: VersionTLS13
      # Reject connections that do not send a SNI header.
      sniStrict: true
